### ISSUE TITLE
Supporting +32 dimensions

### ISSUE THREAD

**Issue by tannerlinsley** [crossfilter/crossfilter#10]
As proposed here: https://github.com/square/crossfilter/pull/75, this could be an awesome feature to **Crossfilter2** (name pending ;)  From the looks of it, it would need some reconsideration and better testing for anything to go forward.  I'd like to hear from @sciyoshi (the original PR creator) on this as well.

**Comment by TomNeyland** [comment]
:+1:

**Comment by tannerlinsley** [comment]
There seem to be quite a few changes that took place in https://github.com/square/crossfilter/pull/75 to make this function.  When I previously tested it, there were a few errors.  I'm not familiar enough with the codebase to understand all of the changes at this point.  But I know it came close.

**Comment by esjewett** [comment]
I honestly have not been able to look at this in detail, but I think the direction of the original pull request is right, in that it allows the use of multiple typed arrays for the filters. I think we could probably work from the base introduced here. @tannerlinsley - would you want to merge the changes from square#75 into a branch in this repo and we can start attacking test failures?

**Comment by tannerlinsley** [comment]
Yeah I'll take care of it.

**Comment by sciyoshi** [comment]
@tannerlinsley @esjewett the latest patch from square#75 was working well for me, and has test cases for filtering with >32 dimensions. I'd welcome you guys to give it a shot and see how it works for you :)

**Comment by tannerlinsley** [comment]
K I've merged in https://github.com/square/crossfilter/pull/75 to a new branch: https://github.com/crossfilter/crossfilter/tree/feature-32-plus-dimensions

**Comment by esjewett** [comment]
I've looked more carefully this morning and I think this is OK. I've made a performance micro-optimization on the for loops in the new code to bring it in line with the rest of the Crossfilter style, but I don't think this optimization makes much of a difference (likely no difference in Chrome, less than 1% difference in other browsers, from what I've seen).

In the discussion on square#75, it seemed that there was originally a bug in filter application that you reported @tannerlinsley , but I don't see any issue at the moment. You?

Regarding the 5% performance penalty on filter operations, I suspect this is almost entirely because we are moving from operations directly on the `filters` array to function calls when testing whether a given record is in the filter. I don't think there is a lot we can do about this, and the abstraction along with the removal of the limitation is probably worth the penalty. I don't think there is any way we can avoid a similar penalty, because even if we switched between the old implementation and this one, it would still require a switch evaluation on every filter test to decide which implementation to use, which would probably be at least as bad. Agreed?

**Comment by tannerlinsley** [comment]
Agreed

**Comment by tannerlinsley** [comment]
I just put this through the ringer on our app, and it worked flawlessly.  Just let the dimensions fly.  I think I got up to like 120+  Speed was still pretty good. I couldn't tell the difference.

**Comment by tannerlinsley** [comment]
It's also passing all tests.

**Comment by sciyoshi** [comment]
Any reason this can't be merged now? Are we waiting for more intensive test cases?

**Comment by gordonwoodhull** [comment]
I'm okay with merging it without better test cases. I would be more comfortable if it were properly tested, but I haven't had time to write them myself. 

We had also talked about releasing it as an alpha for a while. That's something I could help with, if @esjewett doesn't want to deal with the npm and versioning nonsense. I'm pretty familiar with that.

**Comment by esjewett** [comment]
@sciyoshi @gordonwoodhull Better tests would be good, but I'd also be OK merging it. We definitely need to do an alpha. I'm just a flake on this stuff. I'll get it set up. Version "2.0.0-alpha-1"?

**Comment by esjewett** [comment]
Hmmm. "2.0.0-alpha.01" seems more canonical and gives us room to grow, as it might be a while before we do a full 2.0 release. Will go with that.

**Comment by gordonwoodhull** [comment]
I think semver wants "2.0.0-alpha.2" (with a dot). Technically 1.4.* is probably also ok since this doesn't break the interface, right?

**Comment by esjewett** [comment]
Either -alpha-2 or -alpha.2 is OK because the dash character is allowed as a character after the dash. But the identifiers are supposed to be dot-seperated after the dash, so I agree that alpha.01 is right. I just published alpha.01 without this merged. Will now merge and publish alpha.02 with the 32+ dimension support.

**Comment by esjewett** [comment]
Anyone have any brilliant ideas on how to test if https://github.com/crossfilter/crossfilter/issues/19 is still an issue under this patch? The fixes are not merge-able, obviously. I think @sciyoshi's rewrite fixed the original problem, but struggling to test. I will publish alpha.02 anyway.

**Comment by gordonwoodhull** [comment]
Just tested it. It was pretty easy to spot by putting a breakpoint on the arrayWiden. I'm not sure if this is a comprehensive test but I saw the widen get hit for a page that shouldn't need it (the dc.js main page) with 1.3.11 but not with 2.0.0-alpha.01

**Comment by esjewett** [comment]
Nice - thanks!
