### ISSUE TITLE
angularjs controller params Change without reload is breaking on Chrome at ndx.groupAll.

### ISSUE THREAD

**Issue by Shirazhussain** [crossfilter/crossfilter#107]
1)I'm using Angularjs 1 and crossfilter is working fine on controller load in all browsers but not on controller parameters change.
2)it is showing "Aw. snap" at ndx.groupAll on chome Version 66.0.3359.117 (Official Build) (64-bit) and higher while working fine with safari and firefox.

**Comment by esjewett** [comment]
Hi,

You'll need to provide an example of what you're actually trying to do. I'd suggest that you do this on StackOverflow with the 'crossfilter' tag rather than here, as we'd prefer to keep this space only for actual problems identified with the library or improvements suggested. If your question results in identifying a bug, then definitely open an issue here.

Thanks!
Ethan
