### ISSUE TITLE
Types for `reduce()` function are too restrictive

### ISSUE THREAD

**Issue by beaugunderson** [crossfilter/crossfilter#119]
The dc.js documentation shows an example of reducing a crossfilter dimension to an array, for when a reduction needs access to all the rows.

The [example](https://github.com/dc-js/dc.js/wiki/FAQ#do-reductions-that-require-all-the-row-data) given is this:

```js
  function groupArrayAdd(keyfn) {
      var bisect = d3.bisector(keyfn);
      return function(elements, item) {
          var pos = bisect.right(elements, keyfn(item));
          elements.splice(pos, 0, item);
          return elements;
      };
  }

  function groupArrayRemove(keyfn) {
      var bisect = d3.bisector(keyfn);
      return function(elements, item) {
          var pos = bisect.left(elements, keyfn(item));
          if(keyfn(elements[pos])===keyfn(item))
              elements.splice(pos, 1);
          return elements;
      };
  }

  function groupArrayInit() {
      return [];
  }

  var runAvgGroup = runDimension.group().reduce(groupArrayAdd(exptKey), groupArrayRemove(exptKey), groupArrayInit);
```

This works great for me but to satisfy typescript I have to cast the add, remove, and init functions to `any` because the type definitions don't allow for an array as the first argument.

**Comment by esjewett** [comment]
I believe this is the same issue discussed in #116. I believe the issue is that `TGroupValue` should not extend `NaturallyOrderedValue` here: https://github.com/crossfilter/crossfilter/blob/master/index.d.ts#L68

Any chance you could try changing that locally in your d.ts file and see if it resolved this issue? If so, we'll change it. I just don't have a good way to quickly test this.
