### ISSUE TITLE
crossfilter.all() method?

### ISSUE THREAD

**Issue by tannerlinsley** [crossfilter/crossfilter#12]
It would be great to not have to keep a copy of the raw data around if one could simply call an `.all()` method on the crossfilter instance and get back a raw array of the rows.

There are other ways of doing this with groupings and what not, but I say skip the overhead and provide a means to dump the data.

Thoughts?

**Comment by esjewett** [comment]
I think this is a good idea. The only thing we need to discuss is possibly protecting the internal data structure so that modifying the array returned by crossfilter.all() will not modify the internal data structure. However, since I believe the internal data structure maintains references to the external array elements anyway, I'm not sure if this is important. For example:

```
var xfilter = crossfilter();
var a = {};
var b = {};
xfilter.add([a,b]);
a.test = true;
var dim = xfilter.dimension(function(d) { return d.test; });
console.log(dim.top(Infinity));
```

Which is to say, let's not bother. So we can just modify the crossfilter.js file to return the data:

```
function crossfilter() {
  var crossfilter = {
    add: add,
    remove: removeData,
    dimension: dimension,
    groupAll: groupAll,
    size: size,
    all: function() { return data; }
  };
[...]
```

**Comment by tannerlinsley** [comment]
PR #13
