### ISSUE TITLE
Small release before 1.5?

### ISSUE THREAD

**Issue by TijmenW** [crossfilter/crossfilter#144]
Will there be a small patch version of the 3 commits not currently part of the latest version before the ES6 upgrade?

**Comment by gordonwoodhull** [comment]
Yes. I am currently planning to release 1.4.8 and 1.5 at the same time, in the next couple of weeks.

Master plus any fixes which are ready that don't need ES6 will go into 1.4.8.

Built-in sort #122 and the ES6 changes will go into 1.5.

**Comment by gordonwoodhull** [comment]
Since I got stuck on #134, I'm not sure what to do. 

I think it's important to restore typed arrays in a version 1.4.* targeting ES5. But later changes rely on the arrays being untyped, so it will take some debugging and fixes.

I see three choices:

1. I could release 1.4.8 with the other fixes, and continue with the ES6 changes in 1.5. But this would mean we would need a longer-term "support branch" for 1.4.*, since restoring the typed arrays has to happen sometime. (This could an actual git branch or just starting 1.4.9 from the 1.4.8 tag.)
2. Hold on for #134 before doing anything
3. Release 1.4.8 but hold on for #134 before releasing 1.4.9 and 1.5 simultaneously

In any case, I have a couple of deadlines this week, so no releases will happen until Friday Nov 8. Any feedback is welcome.

**Comment by gordonwoodhull** [comment]
Version 1.4.8 is published!

https://github.com/crossfilter/crossfilter/releases/tag/1.4.8

**Comment by TijmenW** [comment]
When is it going to be published on NPM and cdnjs?

**Comment by gordonwoodhull** [comment]
Thanks, I went straight into 1.5 and forgot npm. 1.4.8 is published on NPM now.

As of a week ago CDNJS [seemed to be in trouble](https://github.com/cdnjs/cdnjs/issues/13524), so it might take some time to land there.

unpkg is not quite as reliable but always up to date:
https://unpkg.com/browse/crossfilter2@1.4.8/crossfilter.js
