### ISSUE TITLE
jsonstat -> crossfilter

### ISSUE THREAD

**Issue by acmeguy** [crossfilter/crossfilter#168]
Hi,

We are using the jsonstat specification quite heavily to deliver statistical information. 

This is a higly efficient format that offers dictionary based encoding for compression and for us it has proven to be the 10% of the size of the equivilent csv. 

It has limitations and the tools available to encode/decode (jsonstat-tools) this structure is terribly slow.
We have replaced the toTable and fromTable functions with fast and optimized implementation.

I wander if there is a shortcut available to load into crossfilter that would use the encoded content and load it into the bit-based encoding of Crossfilter.

I'm new to Crossfilter and would like some pointers so I can explore options to get data into crossfilter in a compressed/alread-encoded form.

Any assistance is appreciated :)

**Comment by acmeguy** [comment]
I understand a bit better now how crossfilter works and that it's only during dimension creation that entities are expected/calculated. This allows me to instantiate it with an efficient class that minimizes any overhead.

Thnak you (this can be closed)

**Comment by acmeguy** [comment]
This is what we have implemented now, as well.

Thank you for verifying the approach.

**Comment by gordonwoodhull** [comment]
It may depend on the complexity of the data, but the rule of thumb I use is that crossfilter is good up to 500K rows. After that, it’s better to use a server side solution. (If you are using dc.js, the [commitHandler](http://dc-js.github.io/dc.js/docs/html/BaseMixin.html#commitHandler) helps with this.)

Once you get to that size, the time downloading all that data to the browser also starts to be an issue, so that is extra motivation.
