### ISSUE TITLE
quicksort and insertionsort were removed with no documentation or obvious reason

### ISSUE THREAD

**Issue by Spacarar** [crossfilter/crossfilter#169]
I've used the [crossfilter.quicksort](https://github.com/crossfilter/crossfilter/wiki/API-Reference#_quicksort) function for some time and have recently been writing a package that binds a bunch of dc/crossfilter/d3 stuff to Vue (if you are interested you can check it out [here](https://github.com/geodav-tech/vue-dcjs/)) and I noticed that these sort functions were missing.

I didn't see anything in the documentation or issues about this, but I did notice [this commit](https://github.com/crossfilter/crossfilter/commit/52ce473246daa8387c53595c6ba0915ca2810907) which replaces these functions with an internal sort function that is not exported and is labeled as a chore.

So, I'm left wondering; what was the reason for this change and why wasn't it reflected in any documentation?

Is there an alternative you suggest to the crossfilter quicksort? I haven't done performance tests on my data in some time, but I do remember the crossfilter quicksort was able to save some time on my calculations in the past.

**Comment by Spacarar** [comment]
crossfilter@1.5.4 for reference version

**Comment by gordonwoodhull** [comment]
Hi @Spacarar!

Please see the release notes:

https://github.com/crossfilter/crossfilter/releases/tag/1.5.0

The PR was #122:

Mike recalled in https://github.com/crossfilter/crossfilter/pull/122#issuecomment-496543182 that the only reason it was there was because “typed arrays did not support a sort method” until ES2015.

If it’s performs better for you, you are of course welcome to copy the old code under its license - it originally came from Dart.
