### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by lpgeiger** [crossfilter/crossfilter#35]
Please update release notes so we can know what has changed from Square's legacy crossfilter. Thanks!

**Comment by esjewett** [comment]
We have not had a new release yet. In short, 1.3.* here (and in 'crossfilter2' on NPM) should track the Square Crossfilter 1.3.* release.

1.4.* will be released here and will be based on the current master branch. We are doing alpha releases as 1.4.0-alpha.01, available on NPM. Currently the 1.4 alpha includes the following changes. This is as good a place to track future release notes as any :-)

- crossfilter.all
- Support for more than 32 dimensions (thanks to @sciyoshi)
- Data lifecycle information for group reduce functions (see docs - https://github.com/crossfilter/crossfilter/wiki/API-Reference#wiki-group_reduce)
- onChange callback (needs documentation)
- dimension support for array data type (see docs - https://github.com/crossfilter/crossfilter/wiki/API-Reference#wiki-dimension)

Other features/fixes planned are tracked in the milestone: https://github.com/crossfilter/crossfilter/milestones/1.4.0-rc.01

**Comment by esjewett** [comment]
Draft release notes (let me know if I missed anyone):

Crossfilter 1.4 is the first minor release since the Crossfilter project moved to community stewardship. It includes several new features contributed by multiple members of the Crossfilter community:

 * crossfilter.all allowing access to all the raw data in the Crossfilter, ignoring any filters.
 * Support for more than 32 dimensions. Define as many dimensions as you want. Performance is reduced after 8, 16, and 32 dimensions. Special thanks to @sciyoshi.
 * Data lifecycle information for group reduce functions, allowing the definition of custom groups that selectively ignore filter operations.
 * onChange callback allowing external code to watch for certain types of changes within Crossfilter.
 * Dimension support for array data type (see docs - https://github.com/crossfilter/crossfilter/wiki/API-Reference#wiki-dimension) allowing easy definition of dimensions for fields that contain multiple values.
 * isElementFiltered function to allow external applications to do fancy stuff with filters.
dimension.top and dimension.bottom take an optional offset parameter. Supports pagination-type needs.
 * dimension.accessor allows direct access to the accessor function that defined the dimension. This is the function that was originally passed in through crossfilter.dimension.
String shorthand for creating dimension accessors - #56

Thanks to @betalb, @drarmstr, @esjewett, @gordonwoodhull, @MarkHerhold, @nreese, @r4j4h, @sciyoshi, @tannerlinsley, and @TomNeyland for contributions to this release.
