### ISSUE TITLE
Release Process: Please Tag Alpha Releases

### ISSUE THREAD

**Issue by MarkHerhold** [crossfilter/crossfilter#45]
I had no idea there was an alpha release out. (:+1: BTW)

When publishing, please consider the use of `npm version`, which creates a git tag and push with `git push --tags` so it shows up in [releases](https://github.com/crossfilter/crossfilter/releases)!

**Comment by esjewett** [comment]
We've been doing this, but it's a mess. We originally thought we were going to release v2.0, so there are several 2.0 alphas, but the latest is 1.4, so the latest alpha tag is 1.4.0-alpha.01. You can see it if you click "show 6 newer tags" on the releases page. It looks like there is a manual step we have to take as well in order to make the release show up on the page by default.

**Comment by esjewett** [comment]
They should show up on the releases page now :-) And 1.4.0-alpha.01 is on npm, but you have to specify  is exactly, is my understanding. There have also been several changes since 1.4.0-alpha.01, so we are due for a 1.4.0-alpha.02. I will try to get that out soon.
