### ISSUE TITLE
Allow to select top/bottom records from dimension without applying dimension filter

### ISSUE THREAD

**Issue by betalb** [crossfilter/crossfilter#63]
It would be helpful to get behavior similar to group/groupAll, when filter for dimension is not applied, and select all the rows that satisfy every filter except that particular dimension

**Comment by esjewett** [comment]
I'm trying to understand what this would be used for. Can you explain a bit more what your use-case looks like?

**Comment by gordonwoodhull** [comment]
Probably @betalb is referring to the strange inconsistency where `group.all()`_does not_ observe the current dimension's filters, but `dimension.top()`_does_:

> This method intersects the crossfilter's current filters, returning only records that satisfy every active filter (including this dimension's filter)

https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_top

**Comment by esjewett** [comment]
Yup, that I understand. But strangely enough, that inconsistent behavior matches the common use case. I'm wondering what @betalb is doing where a different behavior is required.

**Comment by skidr0w** [comment]
@esjewett I also would like this functionality. I am integrating a [parallel coordinates chart](https://github.com/syntagmatic/parallel-coordinates) with dc.js. The parallel coordinates chart only uses it's own dimension and no grouping. The problem I'm facing is, that the parallel coordinates chart can't get all records from it's dimension ignoring its own filter. So for now, only the filtered data is visible. Do you know a workaround to fix this issue?

**Comment by esjewett** [comment]
@skidr0w Hmmm. So you're trying to use a filterFunction to apply the parallel coordinate filters onto the Crossfilter? I wonder if the best approach might be to make `crossfilter.allFiltered` take an `[ignoredDimensions]` argument like `crossfilter.isElementFiltered` does.

**Comment by skidr0w** [comment]
@esjewett Yes, that is correct. I use dimension.filterFunction for filtering and this works perfectly. But for displaying the records in the parallel coordinates chart I tried to use dimension.top(Infinty), but this only shows records which match the filter in this dimension aswell. The result is, that the parallel coordinates does only show records which match its own filters, which is not the desired behaviour. It should also show the records which does not match its own dimension. Similar to the behaviour as dimension.group().

Your proposed solution with crossfilter.allFiltered where I can pass the dimension which filters should be ignored should work for my problem. I don't know how much effort this is to implement. I haven't yet looked into the crossfilter codebase.

**Comment by esjewett** [comment]
@skidr0w It's not bad, I think. Would you like to send a pull request? You would need to copy the code to build a mask from `isElementFiltered` and add it to `allFiltered`, then call `filters.zeroExceptMask` instead of `filters.zero`.

I would suggest refactoring the mask code out of `isElementFiltered` into its own function, but I think `isElementFiltered` is often called in tight loops and I'm not up to speed on whether function invocation still has overhead in modern JS engines or if they are inlining code now. Anyone? @gordonwoodhull? @tannerlinsley?

**Comment by gordonwoodhull** [comment]
Mmy understanding is that function calls are "free" as long as they are not polymorphic. Inside crossfilter, each function call *should* always involve the same types. But it's probably worth keeping an eye on the performance tests to be sure.

**Comment by skidr0w** [comment]
@esjewett I made a pull request for this feature. Do you mind to review my changes? Thank you.

**Comment by pierreleripoll** [comment]
Hi ! It's my first time modifying a wiki entry on github, I thought it would automatically run a pull request to be reviewed and approved then merged. But apparently we can just modify the wiki right away ...

[Here's my change](https://github.com/crossfilter/crossfilter/wiki/API-Reference/_compare/312475f549340cda71aa9867145810a3b27b2cc9...1b4a4e1cd0a7979e1d7795b40d9385318f86741a), it directly refers to change from this pull request #101 and this opened issue.

I think this issue should be closed since the pull request was merged and the wiki is now correctly updated.

**Comment by gordonwoodhull** [comment]
Thanks for the update, @pierreleripoll! Your edits are helpful and accurate.

We have a glitch in our workflow because the wiki is a separate process, so we can't review docs as part of a PR. Thus they often get missed.

Please feel free to make further edits if you see other changes that have been missed.
