### ISSUE TITLE
Strange behaviour for Crossfilter group function

### ISSUE THREAD

**Issue by ttourwe** [crossfilter/crossfilter#66]
I've noticed the group function in Crossfilter doesn't behave as expected. See [this](http://stackoverflow.com/questions/39455989/strange-behaviour-for-crossfilter-group-function) Stackoverflow post for more details. 

Basically the return value doesn't seem to include the keys generated by the groupValue function. Sometimes it does, sometimes it doesn't, and I didn't manage to understand why this happens. 

Tom

**Comment by esjewett** [comment]
Was @gordonwoodhull's answer in the Github issue an explanation of why this happens? I'm thinking we need further similar explanation in the docs. Do you think that would help?

**Comment by gordonwoodhull** [comment]
I would mildly prefer to create a "Crossfilter Gotchas" section, and link to it from the documentation in a few places.

The documentation is precisely correct, but I think it is a bit terse and mathematical for people to understand in a quick reading. This issue is similar to the unordered `NaN` problem which keeps biting people even when they've read the documentation.

I wonder if it would be possible to write a validation library on top of crossfilter that checks the data and accessors for inconsistencies.

**Comment by esjewett** [comment]
Re. "gotchas" section/page, I think that sounds like a great idea. Whoever is so moved should set it up ;-) I'll get to it eventually, but I'm swamped right now and it looks like it's not getting any better until December at the earliest.

Re. a validation library. I keep going down this path and then deciding it's not worth it. The best I've been able to come up with it doing a quick validation by throwing string, number, NaN, null, and undefined at the dimension accessor and verifying that the values that come back are naturally ordered. That probably gets us 80% of the way there, but it will also throw errors that are irrelevant to people who know that their data doesn't contain nulls, for example. And that approach probably wouldn't have caught this problem because it is so data-dependent. :-(

In any case, I think this type of validation could make sense in a library like Universe. Or I could try to incorporate dimension-accessor function creation into Reductio and for people who have fairly standard use-cases they could just stay on the Reductio rails and there wouldn't be much of a way to get into trouble.

**Comment by gordonwoodhull** [comment]
Re validation: I'd throw the actual data at the accessor functions and test that they return comparable values. It's slow but it could be done in a separate pass. It would be like, oh my charts are broken, let me try this debug mode or validation library.

I think this would not create too many false positives (not any?). I agree it would be easier with Universe (or if crossfilter had getters).

**Comment by esjewett** [comment]
That's a good idea. I wouldn't want this to happen automatically, but how about a `crossfilter.validate` method where we can do a bunch of validation and spit out a validation report of sorts on the console or another logger object?

**Comment by gordonwoodhull** [comment]
I finally contributed a Crossfilter Gotchas page, here's this one:

https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#consistent-dimension-and-group-value-functions

Added links in the documentation. All suggestions welcome!
